spring:
  application:
    name: biblioteca

  datasource:
    url: jdbc:mysql://178.16.140.38:3306/BIBLIOTECA?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: BIBLIOTECA
    password: ClaveRoot123
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      maximum-pool-size: 20
      idle-timeout: 600000        # 10 min
      max-lifetime: 1800000       # 30 min
      connection-timeout: 30000   # 30 seg

  jpa:
    hibernate:
      ddl-auto: update   # âœ… Ya no borra las tablas ni los datos
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: 8085
  address: 0.0.0.0
